Destats 2d for numeric
eda-se/eda pull request #19
Opened 2024-05-29 15:51 UTC by MartynaSokolowska

Podstawowe statystyki 2d numeryczne

2024-05-31 15:09 UTC, Szaroslav requested changes
- Zaktualizuj Pipenva.
  ```bash
  pipenv install scipy~=1.13.1 scikit-learn~=1.5.0 statsmodels~=0.14.2
  pipenv requirements > requirements.txt
  ```
- Zmień nazwę `statistics` na `statistics_1d`.
- Dodaj dwie puste linie między każdą funkcją w `destats.py`.

2024-05-31 15:09 UTC, Szaroslav commented on eda/destats.py
> +def clean_columns(x, y):
Dodaj adnotację typów, będzie to `pd.Series`.

2024-05-31 15:09 UTC, Szaroslav commented on eda/destats.py
> +Równanie: y = {intercept} + {slope}x"""
Zwróć dane, a nie tekst XD

2024-05-31 15:09 UTC, Szaroslav commented on eda/destats.py
> +Przedział ufności dla współczynnika nachylenia: {conf.loc[x.name].tolist()}"""
> Zwróć dane, a nie tekst XD

Tutaj tak samo.

2024-05-31 22:23 UTC, MartynaSokolowska commented
Zrobione, zobacz teraz

2024-06-01 09:56 UTC, Szaroslav requested changes

2024-06-01 09:56 UTC, Szaroslav commented on eda/destats.py
> +    return {"Intercept": intercept, "Współczynnik nachylenia": slope} #"Równanie x": {intercept} + {slope}x}
Wymieszanie polskiego i angielskiego, klucze według mnie powinny być napisane po angielsku małymi literami - intercept i slope.

2024-06-01 09:56 UTC, Szaroslav commented on eda/destats.py
> +    return {"Przedział ufności dla interceptu": conf.loc["const"].tolist(), "Przedział ufności dla współczynnika nachylenia": conf.loc[x.name].tolist()}
> Wymieszanie polskiego i angielskiego, klucze według mnie powinny być napisane po angielsku małymi literami...

Tak samo tutaj.

2024-06-01 09:56 UTC, Szaroslav commented on eda/destats.py
> +
Dodatkową linię poproszę.

2024-06-01 12:51 UTC, Szaroslav approved these changes

2024-06-01 16:10 UTC, merged