CSV input
eda-se/eda pull request #4
Opened 2024-05-09 17:17 UTC by MadMach420

Prosty input akceptujący tylko CSV, na podstawie CSV tworzona tabela. Na ten moment w zasadzie zero cssa. Przy okazji na potrzeby testów wrzucam przykładowy plik CSV.

2024-05-10 21:05 UTC, Szaroslav requested changes
Preferowałbym `"` jako standardowy znak dla ciągów znaków. Jeśli ci działa aplikacja, mając `app.py` w korzeniu, to przenieś go proszę. Nazwy katalogów powinny być krótkie, napisane małymi literami ([PEP 8](https://peps.python.org/pep-0008/#package-and-module-names)). Zmień nazwę katalogu `src` na `eda`.

2024-05-10 21:05 UTC, Szaroslav commented on src/FileInput/csv_parser.py
> +        return "Invalid content type"
Rzućmy tutaj wyjątek lub `None`, a wyżej dopiero dodajmy tekst jako wiadomość.

2024-05-10 21:05 UTC, Szaroslav commented on assets/Zeszyt1_akt.csv
Zmień nazwę tego arkusza na język angielski, np. `example_data.csv`.

2024-05-18 14:43 UTC, MadMach420 commented on src/FileInput/file_input.py
> +            return dash.no_update, html.Div(result)
Tak, zależnie od wyniku wczytania pliku aktualizowany jest inny komponent

2024-05-18 14:46 UTC, MadMach420 commented on src/FileInput/file_input.py
> +    def handle_file(contents):
Nie, to jest plik wgrany przez użytkownika, nie wiem jakiego typu używa Dash, a w dokumentacji nie mogłem tego znaleźć, więc zostawiłem bez adnotacji

2024-05-18 14:49 UTC, MadMach420 commented on src/FileInput/file_input.py
> +    def handle_file(contents):
Nazwa argumentu zmieniona na content, chociaż moim zdaniem bardziej czytelne jest to, gdy argument ma tę samą nazwę co własność komponentu (jej nazwy nie da się zmienić)

2024-05-18 15:04 UTC, merged